export const CONTACT_LIST='Contacts'
export const CREATE_CONTACT='Create Contact'
export const CONTACT_DETAIL='Contact detail'
export const SETTINGS='Settings'
export const LOGIN='Login'
export const SIGNUP='Signup'
export const HOME_NAVIGATOR='Home'
export const LOGOUT='LOGOUT'